import Inferno from 'inferno';

export default function CssTests({ children })
{
    return (
<header class="{renderingData.app.classNames.top}">
	<h1>CSS-in-JS Inferno Tests</h1>
</header>
<div class="{renderingData.app.classNames.container}">
    <section class="{renderingData.app.classNames.itemContainer}">
        <header class="{renderingData.app.classNames.title}">
            <h2>Main app</h2>
        </header>
{renderComponentList('item', appData.itemNumber, appData, renderingData)}
        <button class="{renderingData.app.classNames.button}">Update</button>
    </section>
    <div class="{renderingData.app.classNames.sideContainer}">
        <aside class="{renderingData.app.classNames.help}">
            <header class="{renderingData.app.classNames.title}">
                <h2>Help</h2>
            </header>
            <p>There is a main section.</p>
            <p>And, beside this one which provides a succint help, there is also an aside controlled by a library. This paragraph is long enough to wrap...</p>
        </aside>
        <aside class="{renderingData.app.classNames.libraryContainer}">
            <header class="{renderingData.app.classNames.title}">
                <h2>3rd Party Library</h2>
            </header>
            <!-- Code generated by the library -->
            <div class="container">
                <span class="counter">101</span>
                <button class="button">Increment</button>
            </div>
        </aside>
    </div>
</div>
<footer class="{renderingData.app.classNames.bottom}">
    <small>The CSS-in-JS Performance Test</small>
</footer>
        <div>
            { children }
        </div>
    );
}
