import Inferno from 'inferno';
import Component from 'inferno-component';

class SecondarySection extends Component
{
	constructor(props)
	{
		super(props);
		this.state =
		{
			value: props.value,
			classNames: { secondaryContainer: 'SecondaryContainer' },
		};
	}

	render(props, state)
	{
		return (
<aside className={state.classNames.secondaryContainer}>
	<header className={props.appClassNames.title}>
		<h2>3rd Party Library</h2>
	</header>
{/* Code generated by the library */}
<div class="container">
<span class="counter">{state.value}</span>
<button class="button">Increment</button>
</div>
</aside>
		);
	}
}

export default SecondarySection;
